package doremi.view;

/**
 *
 * @author João Carlos Luis Pereira
 *
 */
public class FTelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public FTelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarraInicial = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMICantor = new javax.swing.JMenuItem();
        jMIGenero = new javax.swing.JMenuItem();
        jMIMusica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros");

        jMICantor.setText("Cantor");
        jMICantor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICantorActionPerformed(evt);
            }
        });
        jMenu1.add(jMICantor);

        jMIGenero.setText("Genero");
        jMIGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGeneroActionPerformed(evt);
            }
        });
        jMenu1.add(jMIGenero);

        jMIMusica.setText("Musica");
        jMIMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMusicaActionPerformed(evt);
            }
        });
        jMenu1.add(jMIMusica);

        jMenuBarraInicial.add(jMenu1);

        jMenu2.setText("Tocar musicas");
        jMenuBarraInicial.add(jMenu2);

        jMenu3.setText("Sair");
        jMenu3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenu3StateChanged(evt);
            }
        });
        jMenuBarraInicial.add(jMenu3);

        setJMenuBar(jMenuBarraInicial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenu3StateChanged
        this.dispose();
    }//GEN-LAST:event_jMenu3StateChanged

    private void jMIGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGeneroActionPerformed
        FGenero gen = new FGenero();
        gen.setLocation(this.location().getLocation());
        gen.setDefaultCloseOperation(gen.DO_NOTHING_ON_CLOSE);
        this.dispose();
        gen.show();
    }//GEN-LAST:event_jMIGeneroActionPerformed

    private void jMICantorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICantorActionPerformed
        FCantor cant = new FCantor();
        cant.setLocation(this.location().getLocation());
        cant.setDefaultCloseOperation(cant.DO_NOTHING_ON_CLOSE);
        this.dispose();
        cant.show();
    }//GEN-LAST:event_jMICantorActionPerformed

    private void jMIMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMusicaActionPerformed
        FMusica music = new FMusica();
        music.setLocation(this.location().getLocation());
        music.setDefaultCloseOperation(music.DO_NOTHING_ON_CLOSE);
        this.dispose();
        music.show();
    }//GEN-LAST:event_jMIMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMICantor;
    private javax.swing.JMenuItem jMIGenero;
    private javax.swing.JMenuItem jMIMusica;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBarraInicial;
    // End of variables declaration//GEN-END:variables
}
